language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install libavahi-compat-libdnssd-dev libjpeg-turbo-progs optipng gifsicle"
  - "npm install -g grunt-cli bower"
script:
  - "npm test"
  - "grunt dist"
